export const movies = [
  {
    name: "Interstellar",
    year: "2014",
    length: "169",
    rating: "8.7",
    imgSrc: "img/interstellar.png",
    vidSrc: "",
  },
  {
    name: "Inception",
    year: "2010",
    length: "148",
    rating: "8.7",
    imgSrc: "img/inception.png",
    vidSrc: "",
  },
  {
    name: "Seven Pounds",
    year: "2008",
    length: "123",
    rating: "7.6",
    imgSrc: "img/seven_pounds.png",
    vidSrc: "",
  },
  {
    name: "Snatch",
    year: "2000",
    length: "102",
    rating: "8.2",
    imgSrc: "img/snatch.png",
    vidSrc: "",
  },
  {
    name: "Sherlock Holmes",
    year: "2009",
    length: "128",
    rating: "7.6",
    imgSrc: "img/sherlock_holmes.png",
    vidSrc: "",
  },
  {
    name: "Fight Club",
    year: "1999",
    length: "139",
    rating: "8.8",
    imgSrc: "img/fight_club.png",
    vidSrc: "",
  },
  {
    name: "Crash",
    year: "2004",
    length: "112",
    rating: "7.7",
    imgSrc: "img/crash.png",
    vidSrc: "",
  },
  {
    name: "The Last Samurai",
    year: "2003",
    length: "154",
    rating: "7.8",
    imgSrc: "img/the_last_samurai.png",
    vidSrc: "",
  },
  {
    name: "American History X",
    year: "1998",
    length: "119",
    rating: "8.5",
    imgSrc: "img/american_history_x.png",
    vidSrc: "",
  },
  {
    name: "The Usual Suspects",
    year: "1995",
    length: "106",
    rating: "8.5",
    imgSrc: "img/the_usual_suspects.png",
    vidSrc: "",
  },
  {
    name: "300",
    year: "2006",
    length: "117",
    rating: "7.6",
    imgSrc: "img/300.png",
    vidSrc: "",
  },
  {
    name: "Dogville",
    year: "2003",
    length: "178",
    rating: "8.0",
    imgSrc: "img/dogville.png",
    vidSrc: "",
  },
  {
    name: "Who Am I",
    year: "2014",
    length: "102",
    rating: "7.4",
    imgSrc: "img/who_am_i.png",
    vidSrc: "",
  },
  {
    name: "Rush",
    year: "2013",
    length: "123",
    rating: "8.1",
    imgSrc: "img/rush.png",
    vidSrc: "",
  },
  {
    name: "The Other Boleyn Girl",
    year: "2008",
    length: "115",
    rating: "6.7",
    imgSrc: "img/the_other_boleyn_girl.png",
    vidSrc: "",
  },
  {
    name: "Law Abiding Citizen",
    year: "2009",
    length: "109",
    rating: "7.4",
    imgSrc: "img/law_abiding_citizen.png",
    vidSrc: "",
  },
  {
    name: "Seven Psychopaths",
    year: "2012",
    length: "110",
    rating: "7.1",
    imgSrc: "img/seven_psychopaths.png",
    vidSrc: "",
  },
  {
    name: "Disconnect",
    year: "2012",
    length: "115",
    rating: "7.5",
    imgSrc: "img/disconnect.png",
    vidSrc: "",
  },
  {
    name: "Fearless",
    year: "2006",
    length: "104",
    rating: "7.6",
    imgSrc: "img/dearless.png",
    vidSrc: "",
  },
  {
    name: "Wanted",
    year: "2008",
    length: "110",
    rating: "6.7",
    imgSrc: "img/wanted.png",
    vidSrc: "",
  },
];
